### ISSUE TITLE
Switch between running on Browserstack and local machine

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [UmangSardesai/serenity-browserstack#1]
Hi, 
Can you please let me know how would create a setup to execute on browser stack for, say, full regression execution, but for development of code, you need to use one's desktop. How can you manage that?

**Comment by UmangSardesai** [comment]
Drop an email to support@browserstack.com. They'll be happy to help you out.

**Comment by rahulkulkarniyahoo** [comment]
They said, they dont support code issue, i guess i will have to find out myself. 
Cheers!
